/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rdl.scrbl;

import java.awt.image.BufferedImage;
//import net.sourceforge.tess4j.ITesseract;
//import net.sourceforge.tess4j.Tesseract;
//import net.sourceforge.tess4j.TesseractException;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //remove unnessasary from the imege
        String basePath = "C:/dev/scrabbleur/images/";
        String imagePath = basePath + "Image001.png";
        String croppedImagePath  = basePath + "Cropped001.png";
        //File imageFile = new File("C:/Javapointers/image.jpg");

        BufferedImage bufferedImage = null;
        try {
            File imageFile = new File(imagePath);
             bufferedImage = ImageIO.read(imageFile);
        }
        catch(IOException ioEx){
            System.err.println("error reading the imae file: ex:" + ioEx);
        }

        if (bufferedImage != null){

            //at x=   32 y=128
            //  at x=630 y=727
            //       598 599
            BufferedImage imageCropped = cropImage(bufferedImage, 32,128,598,599);
            //here we write back the image
            File pathFile = new File(croppedImagePath);
            boolean successWrite =false;
            try {
                successWrite  = ImageIO.write(imageCropped,"png", pathFile);                
            }
            catch(IOException ioex){
                System.err.println("could not writ ethe resulting image");    
            }

            if (successWrite) {
                System.out.println("done th e croppped image");

            }

        } else {
            System.out.println("the read image was null");
        }


         // Set up Tesseract OCR engine
         //ITesseract tesseract = new Tesseract();


        //maybe image recognigtion it too much, just maybe 

    }


    /**
     * Crops an image to the specified region
     * @param bufferedImage the image that will be crop
     * @param x the upper left x coordinate that this region will start
     * @param y the upper left y coordinate that this region will start
     * @param width the width of the region that will be crop
     * @param height the height of the region that will be crop
     * @return the image that was cropped.
     */
    public static BufferedImage cropImage(BufferedImage bufferedImage, int x, int y, int width, int height){
        BufferedImage croppedImage = bufferedImage.getSubimage(x, y, width, height);
        return croppedImage;
    }

}
